### ISSUE TITLE
luaToScriptValue breaks functions with upvalues

### ISSUE THREAD

**Issue by krisr** [cpgf/cpgf#41]
There is some code in the case statement that handles lua functions in luaToScriptValue which attempts to inspect the upvalue. I'm not sure why it's there or what it is supposed to accomplish, but it seems to break function passing from lua to C++ because luaToScriptValue ends up storing a ref to the upvalue instead of the function (presumably because the upvalue is left on the top of the stack?). I've commented this code out in my copy of cpgf for now and would be happy to submit a patch.

Perhaps this is some debugging code and I should not be using the development branch?

**Comment by wqking** [comment]
Fixed a834fe9d08b1ea7dc0eff9a4801e520091730bca
