### ISSUE TITLE
For C++ to return (non-const) char* to script, malloc or new?

### ISSUE THREAD

**Issue by myocytebd** [cpgf/cpgf#51]
A silly question, if I want to expose [char *foo()] to script, how do I allocate the memory?
malloc or new char[]?

Or how to create and return a string native-to-script?

**Comment by myocytebd** [comment]
Let MyString be a copyable like class.

1. How to set policies for these methods?

void A::setName(const MyString &);
According to FAQ/Reflection/1st, GMetaPolicyCopyAllConstReference should be used. Am I right?

MyString A::getName();
A. Does scriptbind copy the return value to another heap allocated MyString?
(Or it will be unsafe for script. OTOH, there seems no policy controlling this behavior.)

B. Should I add GMetaRuleTransferOwnership <-1> ?
Looking at scriptbind code, it seems to set allowGC flag by status of GMetaRuleTransferOwnership,
without trying to deduce a default ownership from meta.

**Comment by wqking** [comment]
Hi,

1, If MyString has any contructor which has only one parameter and no "explicit" (that's to say, MyString can be constructed from another type directly and implicitly), then yes, GMetaPolicyCopyAllConstReference should be used.

2, getName returns the object by value, then nothing policy should be specified. cpgf will copy the returned value on heap, and manage the lifetime in the script engine automatically. That's to say, returning a value means the function already transfer the ownership to the caller or script engine, so you don't need to specify GMetaRuleTransferOwnership.
GMetaRuleTransferOwnership  is used on pointer, such as ```MyString * A::getName();```, which the caller needs to free the returned pointer.

Let me know if anything is not clear. :-)
