### ISSUE TITLE
compile times very long

### ISSUE THREAD

**Issue by tnovotny** [cpgf/cpgf#57]
I have not checked the exact cause, but even in debug mode the compile times for meta classes are very long. I suspect that a good part of this comes from the simulation of variadic templates with the macros in gpp.h.

#define MAX_BASE_COUNT 20
#define GPP_MAX_LIMIT        60
#define G_MAX_ARITY 30

So the question is: Are there any plans to provide a version that uses variadic templates?

**Comment by wqking** [comment]
Hi,

The long compile time is caused by the heavy template use. It's a common problem in all heavy template used libraries, such like Boost.
I'm not sure if variadic template can improve the compile speed. We need to benchmark it.
If variadic template does improve the compile speed significantly, we may rewrite the GPP part with variadic template, then cpgf may go to the C++11 era. At current moment cpgf is C++03 based, not requires C++11.

**Comment by tnovotny** [comment]
It took me a while to find it, but I remembered that STL posted some benchmark results when VS removed their 'faux variadic" stuff from the compiler.

http://blogs.msdn.com/b/vcblog/archive/2013/06/28/c-11-14-stl-features-fixes-and-breaking-changes-in-vs-2013.aspx

Their limit set via VARIADIC_MAX was 5 by default. Increasing it to 10 caused nearly a 50% increase in compile time (2307 ms to 3325 ms). Setting the 'faux variadic' limits of cpgf to some number smaller than 5 may give an indication of the improvement potential. I think I'd try that first. Are there any other defines other than the ones above that influence the template generation?

**Comment by wqking** [comment]
That's really interesting. And if variadic template improves compile speed so much, we will definitely go to the variadic template way and turn cpgf into c++11 based. I myself currently uses C++11 features in one of my closed source project and I really love it.

The major related macros are,
#define MAX_BASE_COUNT 20 // in gmetadefine.h
#define G_MAX_ARITY 30 // in gconfig.h
#define POLICY_MAX_RULES GPP_MAX_LIMIT // in gpolicy.h

**Comment by tnovotny** [comment]
Support for variadic templates (and c++11 in general) would be great.Any thoughts on when that might become a reality. Right now I'm evaluating the library for my purposes. Should I decide that it's the best fit for my needs, I might give it a try myself.

**Comment by wqking** [comment]
No ETA yet. Most likely won't happen very soon. I'm quite busy on my daily work and also my another closed source project, also China Spring Festival is coming.
It's a non-trivial change. At least GCallback should be rewrite completely in C++11 manner.

However, before we turn to C++11, we need to at least approve that reducing the template parameter count can improve compile speed, which can be easily done by changing the numbers we talked above to smaller ones. I will do it when I have time.

**Comment by tnovotny** [comment]
I feared as much. There is a lot of overlap with c++11, so a lot of stuff can be refactored, redesigned or replaced.  I don't have that much time myself, but I might play around with the code some.In the meantime I'll move all the meta stuff into separate files.If I get around to benchmarking, I'll post the results here.

**Comment by tnovotny** [comment]
For a debug compile I get a 4x speedup when I reduce the values to 5
Time Elapsed 00:00:08.78 (original values)
Time Elapsed 00:00:02.12 (reduced values)

**Comment by wqking** [comment]
The benchmark looks promising, thanks for posting it.

**Comment by wqking** [comment]
Hi,

I rewrote GCallback and some code base in reflection using C++11 on the develop branch. I believe that will improve the compile speed. Since we are moving to C++11, all of the other remaining variadic templates simulating macros will be removed.
