### ISSUE TITLE
Reflection of constructor

### ISSUE THREAD

**Issue by sebblonline** [cpgf/cpgf#58]
Hi,

I'm trying to reflect a simple class as you can see in the complete example in the pastebin link (should compile when an appropriate project is set up). Here, I want to reflect a method and the constructor of class MyController. This is done in static void reflect(Define define). Reflection of methods works fine under Linux and Windows, but the reflection of the (non default) constructor does not compile on Linux using GCC 4.8.2. Here something seems to be different in template syntax between Windows and Linux compiler. 
The error is very generic: "expected primary-expression before 'void'" (in line 61)

What is the correct syntax for reflecting this constructor?

http://pastebin.com/pqJiEcL1

Thanks a lot in advance.

Regards
Sebastian

**Comment by wqking** [comment]
Hi,

I did a quick test with MingW GCC 4.9.1, I also got a bunch of compile errors. I will check it.

**Comment by sebblonline** [comment]
I found the problem. Clang gives a more meaningful error message.
See: http://stackoverflow.com/questions/3786360/confusing-template-error
In my example, the line must look like that:
define.template _constructor<...>();

anyway, thanks for your feedback.
sebastian
