### ISSUE TITLE
double underscore defines in header

### ISSUE THREAD

**Issue by tnovotny** [cpgf/cpgf#59]
It is my understanding that your use of double underscores in the defines is not standard conformant.

http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

"Each name that contains a double underscore (_ _) or begins with an underscore followed by an uppercase letter (2.11) is reserved to the implementation for any use."

Basically such user defined tags as include guards are just disasters waiting to happen. #pragma once is much safer and almost unanimously supported.

http://en.wikipedia.org/wiki/Pragma_once

**Comment by wqking** [comment]
Hi,

Did you find any macros start with double underscore? AFAIR I had changed all of them to prefixing with CPGF_

**Comment by tnovotny** [comment]
"reserved [...] for any use."  means it does not need to be a macro. Simply defining something can potentially cause trouble, and should therefore be avoided.  

I did not check the latest code, I downloaded the last official release from 2013. There all the include guards are of the form: __Filename_H.

**Comment by wqking** [comment]
The download was not up to date. Try the github one, all the include guards were changed to CPGF_FILENAME_H
