### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by Mr-Jonas** [cpgf/cpgf#60]
The code looks extremely nice and browsing the samples, it seems that it offers solid functionality.
I need to save object to json and it seems to be able to that.
So is it wise to use this in a new project ?
Thank you

**Comment by svalaskevicius** [comment]
its alive - however the development of new major features has slowed down a bit lately - to which you can also look at as a sign of stability and matureness :)

my 2ct - if it solves a problem for you - then use it :)

**Comment by Mr-Jonas** [comment]
ok. that is super. It solve that problem, I do not have to write save class to json code :)
I hope. Only down side is the doc is not so extended and it can do crazy stuff :) but I hope the samples will lead me into the light :)
Can I exclude stuff to make it less ? Like script binding or is it all or nothing ?

**Comment by svalaskevicius** [comment]
you can :)

see https://github.com/cpgf/cpgf/blob/develop/build/build.config.txt - you can disable all the individual script binding engines :)

**Comment by Mr-Jonas** [comment]
oh. that is nice. I have included the cpp files directly as im in QT and not sure the make files work.
Does these flag translate to #defines so I can use them without the make file?

**Comment by wqking** [comment]
Hi Jonas,

The project is alive, though it's not quite active developed now.

If you include the source code to your project directly, you don't need to care the make flags. You only need to include the files you need, and exclude the files you don't need, such as scripting.
So you can exclude below source folders,
metadata
metatraits
metautility
scriptbind
tween

**Comment by Mr-Jonas** [comment]
Oh - the master himself ,
Hi Wang Qi 
Aha, I did delete the lua ones as it complained for a.h file but I had no idea I could remove that much :)
It turn out saving objects to json was very easy - but Im looking for a bit of insight on how to use the version feature and how to handle format/object change over time. 
I will take a look at the test units to see what wonders it hold :)
Thank you for your time and answers.
