### ISSUE TITLE
How to retrieve a cpgf::GMetaClass when I have only a base class instance?

### ISSUE THREAD

**Issue by zack-snyder** [cpgf/cpgf#63]
In languages with reflection support, it is very common to work with a base class types, and access the derived methods and properties. How can I do this with cpgf?
At the moment I only found `cpgf::findMetaClass` which takes a string. But I have a base object instance, I don't have the actual name...

**Comment by wqking** [comment]
A quick check on iPad, 
	void * castToDerived(const void * self, size_t derivedIndex) const;
should do the work.
Sorry there is no document for it,
Other functions may interest you,
	const GMetaClass * getBaseClass(size_t baseIndex) const;
	size_t getBaseCount() const;

	const GMetaClass * getDerivedClass(size_t derivedIndex) const;
	size_t getDerivedCount() const;

	bool isInheritedFrom(const GMetaClass * ancient) const;

	// return a pointer points to this class
	void * castFromBase(const void * base, size_t baseIndex) const;

	// return a pointer points to base class
	void * castToBase(const void * self, size_t baseIndex) const;

	// return a pointer points to this class
	void * castFromDerived(const void * derived, size_t derivedIndex) const;

	// return a pointer points to derived class
	void * castToDerived(const void * self, size_t derivedIndex) const;

**Comment by zack-snyder** [comment]
I am not sure if this helps me. What is the paramter `derivedIndex` for?
Take a look at following code:
```
struct Base
{
};

struct Derived_A : Base
{
};

struct Derived_B : Base
{
int property = 0;
};
```

```
int main()
{
    Derived_B obj;
    func(obj);
}

void func(Base& obj)
{
  // here I want to print out the name of all properties of obj.
  // but how can I now retrieve here the correct 'GMetaClass'
  // which must be in this example from 'Derived_B'
  // I don't have the knowledge of the correct inheritance level, obj can be anything...
}
```

**Comment by wqking** [comment]
Hi,

With Base & obj, to obtain the real class under it, in pure C++, you have to use dynamic_cast to test if it can be casted to Derived_A or Derived_B, or any class derives from Derived_A or Derived_B, recursively.

This is similar in cpgf meta system. You can call getDerivedCount to get the derived class count, in your case, it's 2. Then call castToDerived to try to cast to each derived class, if any one is successful, it means Base is the super class of it.

I've explained how it works. Fortunately, in cpgf internal code, the similar work is already done.

See "cast" here,
http://cpgf.org/document/script-binding-builtin-library-core.html

GMetaCore::cast is in metautility/gmetacore.cpp.

The more direct code is in src/gmetaapiutil.cpp, see how metaCastToDerived works.

All of above code uses the interface based API, IMetaClass. It should be quite easy to roll our your own version for GMetaClass.
