### ISSUE TITLE
Compiler error from simple code?

### ISSUE THREAD

**Issue by Oooocean** [cpgf/cpgf#65]
I change a01_reflect_to_global.cpp and add a simple funtion "nt test(int *& param) const ":
class Point
{
public:
    Point() : x(0), y(0) {
    }

```
Point(int x, int y) : x(x), y(y) {
}

void extend(int scale) {
    x *= scale;
    y *= scale;
}

int getArea() const {
    return x * y;
}
int test(int *& param) const {
    param = NULL;
}
```

public:
    int x;
    int y;
};
2>  a01_reflect_to_global.cpp
2>E:\Engine\cpgf-develop\include\cpgf/private/gmetainvoke_p.h(180): error C2664: “int cpgf::callback_internal::GCallbackAgent_1<int,int *&>::operator ()(int &) const”: 无法将参数 1 从“int *”转换为“int &”
2>          E:\Engine\cpgf-develop\include\cpgf/private/gmetainvoke_p.h(180): 编译类 模板 成员函数“cpgf::GVariant cpgf::meta_internal::GMetaInvokeHelper<cpgf::GCallback<int (P0)>,cpgf::GFunctionTraits<Signature>,1,int,Policy,false,false>::invoke(void *,const CT &,const cpgf::GVariant *const *,size_t)”时
2>          with
2>          [
2>              P0=int *&
2>  ,            Signature=int (int *&)
2>  ,            

When I compile project "sampleirrlicht", there are some error just like this one. It seems there is a bug when parameters are something like  "Type *&"(reference to pointer). Or am I miss anything?

**Comment by wqking** [comment]
Hi Ocean,

Thanks for the report.
It should be a bug when handling reference to pointer.

For those non-Chinese reader, the Chinese in the OP is error message that 'can't convert parameter 1 from int * to int &". Ocean, I guess it should be "can't convert from int * to int * &" right? Seems your error message missed a lot of characters.

**Comment by Oooocean** [comment]
@wqking 
Thanks for your reply!
Yes, the error message is `can't convert parameter 1 from int * to int &`. If I chang "int *&" to "int *" or "int **", it's OK. But  reference to pointer doesn't work.

**Comment by wqking** [comment]
Fixed in new variant implementation, at commit 60287cc3cad8131746a32fa5f8a3a085e3caa3c2
