### ISSUE TITLE
Sample Reflection fails to build

### ISSUE THREAD

**Issue by DougRogers** [cpgf/cpgf#69]
The include file "cpgf/gtestutil.h" is not found and GTestRegister is not defined.

**Comment by DougRogers** [comment]
I see this is part of glib.  This should be included in the third party directory so that it builds

**Comment by wqking** [comment]
Hi,
the gtestutil.h was in cpgf, not from glib.
It was removed by me in recently refactoring. I will check the issue.
Currently not all samples may work, though the unit tests should work.

**Comment by wqking** [comment]
Hi,
I've fixed the compile errors in the samples on develop branch. Now all samples that not depending on Box2D, SFML, and Irrlicht work correctly.
