### ISSUE TITLE
Missing destroyInplace() on GMetaFundamental

### ISSUE THREAD

**Issue by CodeMouse92** [cpgf/cpgf#74]
A compiler warning is thrown (Clang) because the `GMetaFundamental` class (`gmetafundamental.h`) is marked `final` and derived from the abstract `GMetaTypedItem` class (`gmetacommon.h`), but unlike all other such derived classes, it does not override the abstract function `destroyInPlace()`.

**One** of the following changes is needed:

(1) `GMetaFundamental::destroyInPlace()` be defined,

(2) `GMetaTypedItem::destroyInPlace()` be made non-abstract (not recommended), or

(3) `GMetaFundamental` is made non-`final`.

**Comment by wqking** [comment]
I will look into it.
