### ISSUE TITLE
Undefined Behavior on gcallback

### ISSUE THREAD

**Issue by CodeMouse92** [cpgf/cpgf#75]
Dereferencing a null pointer is undefined behavior, and yet it is done twice in `gcallback.h`. (This advisory came from Clang).

**`gcallback.h::135`**
```c++
return (T)(*(typename std::conditional<std::is_void<T>::value, int, T>::type *)0);
```

> .../cpgf/build/../include/cpgf/gcallback.h:135:14: warning: binding dereferenced null pointer to reference has undefined behavior
      [-Wnull-dereference]

> .../cpgf/build/../include/cpgf/gcallback.h:135:14: warning: indirection of non-volatile null pointer will be deleted, not trap
      [-Wnull-dereference]

---

Also, something similar here flags on the IDE.

**`gcallback.h::144`**

```c++
return *(T *)0;
```

**Comment by wqking** [comment]
Yes, this is UB, but

1. The `*(T *)0` is never really dereferenced, it's used to return as a reference, and the returned reference should not be dereferenced, so it doesn't crash.
2. It happens when a value must be returned.

I will investigate on if there is better work around.
