### ISSUE TITLE
casting GVariant of derived class to base class

### ISSUE THREAD

**Issue by cutepig123** [cpgf/cpgf#78]
if i have a Gvariant t=new Derived
is it possible to get its base class pointer by

fromVariant<Base*>(t)

thanks very much

**Comment by wqking** [comment]
Doing so may give you bad pointer. The proper way is,  
```
static_cast<Base *>(fromVariant<Derived *>(t));
```

**Comment by cutepig123** [comment]
In my case, I have a framework which defines "Base" class, while "Derived" class is defined by user and is created by cpgf reflection. 
So framework does not know "Derived" class.
Any method to cast the pointer when Derived class is unknown?

**Comment by wqking** [comment]
If you know the meta class of both Base and Derived, and you know Base is the first parent of Derived, yes, and you are sure the variant holds an instance of Derived, not any base class or derived class, you can use castToBase. 
```
static_cast<Base *>(metaClassOfDerived->castToBase(fromVariant<void *>(t), 0));
```
If you don't know if Base is the first parent of Derived, you need to traverse the inheritance tree, there are functions for interfaced base API, you may reference it. In gmetaapiutil.cpp, function metaCastToBase

**Comment by cutepig123** [comment]
I tested castToBase, it works. thx very much
