### ISSUE TITLE
Memory leakage detected with MFC library

### ISSUE THREAD

**Issue by Max-Sum** [cpgf/cpgf#79]
#include <afxwin.h>         // MFC core and standard components
    #ifdef _DEBUG
    #define new DEBUG_NEW
    #endif
    GDefineMetaClass<BodyDeviceModel, DeviceModelBase>
	::declare("BodyDeviceModel")
	._field("w", &BodyDeviceModel::w)
	._field("h", &BodyDeviceModel::h)
	;
When running the code above with VS2010, memory leakage is reported. I am not sure if this is a real problem or just a false alarm.

    Detected memory leaks!
    Dumping objects ->
    {523} normal block at 0x00000000020682B0, 80 bytes long.
     Data: <  `             > 01 00 60 00 CD CD CD CD C0 82 06 02 00 00 00 00 
    {522} normal block at 0x0000000002068210, 48 bytes long.
     Data: <                > 10 82 06 02 00 00 00 00 10 82 06 02 00 00 00 00 
    {521} normal block at 0x0000000002068190, 16 bytes long.
    ......

**Comment by Max-Sum** [comment]
I just found the same problem in RTTR repo. It seems Visual Studio will report anything in global section as a memory leaks. However I am still wondering since I use declare instead of define, which should not add the meta data in global section. Does cpgf define some global variables anyway?
https://github.com/rttrorg/rttr/issues/161

**Comment by wqking** [comment]
VC will report non-freed global data as memory leak. So it's not a problem.
The memory leak you need to care is that growing the memory continuously and never gets freed.
cpgf uses global variables.

**Comment by cutepig123** [comment]
I also has this problem and It seems due to global variable initialization sequence problem

the original code (has memory leakage):
GScopedPointer<GOrderedStaticUninitializerManager> orderedStaticUninitializerManager;
void addOrderedStaticUninitializer(GStaticUninitializationOrderType order, const GStaticUninitializerType & uninitializer)
{
	if(! orderedStaticUninitializerManager) {
		orderedStaticUninitializerManager.reset(new GOrderedStaticUninitializerManager());
	}

	orderedStaticUninitializerManager->add(order, uninitializer);
}

After move the variable into the function, leakge problem is solved:

void addOrderedStaticUninitializer(GStaticUninitializationOrderType order, const GStaticUninitializerType & uninitializer)
{
	static GScopedPointer<GOrderedStaticUninitializerManager> orderedStaticUninitializerManager;
	if(! orderedStaticUninitializerManager) {
		orderedStaticUninitializerManager.reset(new GOrderedStaticUninitializerManager());
	}

	orderedStaticUninitializerManager->add(order, uninitializer);
}

**Comment by wqking** [comment]
@cutepig123 Yes, you are right, orderedStaticUninitializerManager being global won't be freed automatically. Moving it to the function will make the compiler frees it automatically.
I will apply the fix, thanks.
BTW, GScopedPointer  was removed in the latest commit.

**Comment by wqking** [comment]
Fixed a61ca0dcc57efebbd533101eab3f526c8e2382ca
