### ISSUE TITLE
Crash on Unload of library

### ISSUE THREAD

**Issue by ErrorFlexXx** [cpgf/cpgf#82]
Hello,

last days, I updated my version of cpgf to the latest master and since then, I get a crash on linux if the application unloads the lib (so after exit(0)).

I did some tracing and found the commit, which is causing the problem for me:
6c8c096682cb143c7cde3314849e74e369e0ac07 (_Replaced cpgf shared pointers with C++ ones._)

Additional informations:

- Since the crash happens, if the lib unloads, it has to be some static variable, which gets unloaded.
- If I don't load a script in my code, the crash happens anyway.
- If I don't call GDefineMetaClass in my code, the crash is gone.

Let me know, if you need any further informations.

Regards

**Comment by wqking** [comment]
Fixed.

Reproduce step:  
1, The OS should be Linux (I tested on Ubuntu).  
2, Compile cpgf as shared library with Lua enabled. (in build.config.txt, set HAS_LUA to 1, and LIB_SHARED to 1).  
3, `make linux TARGET=samplelua`  
4, `./bin/samplelua`  
Segmentation fault

**Comment by ErrorFlexXx** [comment]
Confirmed, the bug is fixed.

Many thanks for your great help!
