### ISSUE TITLE
Failed compile cpgf 1.6.1 with v8 libs under visual c++ 2015

### ISSUE THREAD

**Issue by ivanK7** [cpgf/cpgf#85]
Сompiler cannot find some objects as the necessary files are apparently missing:
`.\cpgf\src\scriptbind\gv8bind.cpp(61): error C2504: 'GShareFromBase': base class undefined
 .\cpgf\src\scriptbind\gv8bind.cpp(172): error C2504: 'GUserData': base class undefined`

**Comment by wqking** [comment]
:( Sorry, I should have mentioned in the readme, V8 and Mozilla SpiderMonkey support is not update to date, so you can't build with V8 now. The reason is it's too difficult to build and test V8.

**Comment by ivanK7** [comment]
I understand that V8 is a rather complicated library and I have the opportunity to test its work. But in this case some source files were lost, I suspect that this is the result of the transition from version 1.5 to version 1.6. For example, the GShareFromBase object is present in the file .\cpgf\gsharedptr.h version 1.5.6, but not in the source files of version 1.6.1.

**Comment by wqking** [comment]
Yes, V8 is expected to be broken in cpgf. The core engine was changed a lot, and Python/Lua engine were updated, but V8 was never updated.
You can't wish V8 can work in cpgf.

**Comment by ivanK7** [comment]
Ok. I will try to fix it myself.
Thank you, quick reply!

**Comment by wqking** [comment]
Thanks for your effort. If you do it, feel free to open PR.
But it's not as simple as those missing files, the internal V8 binding engine should be fixed. You can see how I did on Python and Lua.
