### ISSUE TITLE
possible misprint

### ISSUE THREAD

**Issue by PeterMoroz** [cpgf/cpgf#86]
I believe that file gsetter.h (include/cpgf/accessor/gsetter.h) has mistake in the line 133 .
Instead of 		PolicyHasRule<Policy, **GMetaRuleGetterExplicitThis**>::Result
should be 		PolicyHasRule<Policy, **GMetaRuleSetterExplicitThis**>::Result

**Comment by wqking** [comment]
I think you are correct. I will do a fix and do some test.

**Comment by wqking** [comment]
Fixed 912a5cfa4d5c09218608179cb79a9940cce33f06
